version: 0.0
os: linux
files:
  - source: backend/server
    destination: /backend
  - source: frontend/build
    destination: /frontend

hooks:
  # ApplicationStop:
  #   - location: backend/stop_server.sh
  ApplicationStart:
    - location: backend/start_server.sh
      timeout: 120