version: 0.0
os: linux
files:
  - source: backend/server
    destination: /backend
  - source: backend/server_start.sh
    destination: /backend
  - source: frontend/build
    destination: /frontend

hooks:
  ApplicationStart:
    - location: backend/start_server.sh
      timeout: 120