version: 0.0
os: linux
files:
  - source: backend/server
    destination: /backend
  - source: frontend/build
    destination: /frontend
  - source: frontend/media
    destination: frontend/media
  - source: scripts/
    destination: /scripts

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  BeforeInstall:
    - location: scripts/before_install.sh
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120