// Code generated by go generate; DO NOT EDIT.
package main

import (	
	"net/http"
	"github.com/mholt/binding"
)

// FieldMap is auto-generated from struct tags to provide bindings for with mholt/binding
func (p *PostRequest) FieldMap(r *http.Request) binding.FieldMap {
	return binding.FieldMap {
		&p.FilterBy: "filter-by",
		&p.IDs: "ids",
		&p.Num: "num",
		&p.Raw: "raw",
		&p.SortBy: "sort-by",
		&p.Summary: "summary",
	}
}
