CREATE TABLE post(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255) UNIQUE,
    summary varchar(255),
    content text
);

CREATE TABLE tag(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value varchar(50)
);

CREATE TABLE post_tag(
    post_id int REFERENCES post (id),
    tag_id int REFERENCES tag (id)
);