CREATE TABLE post(
    post_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255),
    summary varchar
    content text
)

CREATE TABLE tag(
    tag_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value varchar(50)
)

CREATE TABLE post_tag(
    post_id int PRIMARY KEY REFERENCES post,
    tag_id int PRIMARY KEY REFERENCES tag
)